// Regenerates apps/web/src/phone-route-corpus.ts: the hands mobile Practice's
// fixed board is sized against. Seeded, so the output is reproducible.
//
//   node scripts/gen-phone-route-corpus.ts
//
// It plays 20,000 four-seat hands (two partner hands to every cut throat hand,
// half with the double-six forced) by random legal moves and keeps the 400
// whose longest end is longest -- 16 bones or more, doubles as tie-break. Those
// are the hands that run out of wood; ordinary hands never come close.
import { writeFile } from 'node:fs/promises';
import { applyMove, deal, legalMoves, type TileId } from '../packages/engine/src/index.ts';

const HANDS = 20000;
const KEEP = 400;
let seed = 7;
const rand = () => { seed = (seed * 1664525 + 1013904223) >>> 0; return seed / 4294967296; };
const tiles: string[] = [];
for (let a = 0; a <= 6; a++) for (let b = a; b <= 6; b++) tiles.push(`${a}-${b}`);
const isDouble = (tile: string) => tile.split('-')[0] === tile.split('-')[1];

const hands: Array<{ code: string; hardness: number }> = [];
for (let k = 0; k < HANDS; k++) {
  const order = [...tiles];
  for (let i = order.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1));
    [order[i], order[j]] = [order[j], order[i]];
  }
  let hand = deal({
    order: order as TileId[], seatCount: 4, mode: k % 3 ? 'partner' : 'cutthroat',
    useBoneyard: false, poseMustBeDoubleSix: k % 2 === 0, poser: 0,
  });
  for (let guard = 0; guard < 300 && hand.status === 'active'; guard++) {
    const moves = legalMoves(hand);
    if (!moves.length) break;
    hand = applyMove(hand, moves[Math.floor(rand() * moves.length)]);
  }
  const pose = hand.moveLog.find((move) => move.kind === 'pose');
  if (!pose || pose.kind !== 'pose') continue;
  let code = isDouble(pose.tile) ? 'D' : 'o';
  const count = { left: [0, 0], right: [0, 0] };
  for (const move of hand.moveLog) {
    if (move.kind !== 'play') continue;
    const double = isDouble(move.tile);
    code += move.end === 'left' ? (double ? 'L' : 'l') : (double ? 'R' : 'r');
    count[move.end][0] += 1;
    if (double) count[move.end][1] += 1;
  }
  const long = count.left[0] >= count.right[0] ? count.left : count.right;
  hands.push({ code, hardness: long[0] * 10 + long[1] });
}
// Stable sort keeps the seeded order among equals.
const kept = hands.map((h, i) => ({ ...h, i }))
  .sort((a, b) => b.hardness - a.hardness || a.i - b.i)
  .slice(0, KEEP)
  .map((h) => h.code);

const lines = [];
for (let i = 0; i < kept.length; i += 6) lines.push(`  '${kept.slice(i, i + 6).join(' ')}',`);
await writeFile(new URL('../apps/web/src/phone-route-corpus.ts', import.meta.url), `// Generated by scripts/gen-phone-route-corpus.ts -- do not edit by hand.
//
// The ${KEEP} hardest of ${HANDS.toLocaleString('en-US')} simulated four-seat hands for mobile Practice's
// fixed board. One hand per word: D or o for a double or ordinary pose, then
// each play in order -- l/r for an ordinary bone on the left/right end, L/R
// for a double.
export const PHONE_ROUTE_CORPUS: readonly string[] = [
${lines.join('\n')}
].join(' ').split(' ');
`);
console.log(`kept ${kept.length} hands`);
